{
 "title": "Biconomy Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Biconomy Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "biconomy_version" }
   ]
  },
  {
   "title": "Node Address",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "biconomy_node_info" }
   ]
  },
  {
   "title": "Gas Premium",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "biconomy_gas_premium_percentage"
    }
   ]
  },
  {
   "title": "Beneficiary Address",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "biconomy_node_info" }
   ]
  },
  {
   "title": "Uptime Timeline",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "seconds" } },
   "targets": [
    { "expr": "biconomy_chain_uptime_seconds", "legendFormat": "{{Name}}" }
   ]
  },
  {
   "title": "Current Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "seconds" } },
   "targets": [
    { "expr": "biconomy_chain_uptime_seconds", "legendFormat": "{{Name}}" }
   ]
  },
  {
   "title": "Chain Overview",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "biconomy_chain_info" }
   ]
  }
 ]
}